name: frontend-1.0.$(Build.BuildId)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
    - '*.yml'

variables:
  - name: artifactName
    value: 'frontend'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    echo "Creating package directory..."
    mkdir -p $(Build.ArtifactStagingDirectory)/package

    echo "Installing dependencies into package folder..."
    # This copies 'requests', 'flask', etc. directly into the artifact
    pip install -r requirements.txt --target $(Build.ArtifactStagingDirectory)/package

    echo "Copying application files..."
    cp -r static $(Build.ArtifactStagingDirectory)/package/ || echo "No static folder found"
    cp -r templates $(Build.ArtifactStagingDirectory)/package/ || echo "No templates folder found"
    cp app.py $(Build.ArtifactStagingDirectory)/package/
    cp requirements.txt $(Build.ArtifactStagingDirectory)/package/
    
    echo "Verifying package contents (requests should be visible here):"
    ls $(Build.ArtifactStagingDirectory)/package
  displayName: 'Install Dependencies and Package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/package'
    artifact: '$(artifactName)'
    publishLocation: 'pipeline'
  displayName: 'Publish Frontend Pipeline Artifact'
