trigger: none

#pool:
#  name: student-lab-pool

variables:
  - name: projectName
    value: 'Training-Trainer-OC12'            # <-- Update this
  - name: buildPipelineName
    value: 'finweb_brad_build'          # <-- Update this
  - name: artifactName
    value: 'frontend'        
  - name: targetFile
    value: 'app.py'                             # Optional: Which file inside artifact to display
  - name: resourceGroup
    value: 'Training-Trainer-OC012'        # <-- Update this
  - name: webAppName
    value: 'finweb-brad'                # <-- Update this Azure Web App target

steps:
- script: |
    echo "Installing Azure DevOps CLI extension..."
    az extension add --name azure-devops || echo "Already installed."

    echo "Logging into Azure DevOps CLI using PAT..."
    echo "$(MY_DEVOPS_PAT)" | az devops login

    echo "Setting DevOps defaults..."
    az devops configure --defaults organization=https://dev.azure.com/opscosolutions project=$(projectName)

    echo "Resolving Pipeline ID for: $(buildPipelineName)..."
    PIPELINE_ID=$(az pipelines show --name "$(buildPipelineName)" --query id --output tsv)

    if [ -z "$PIPELINE_ID" ]; then
      echo "Pipeline not found!"
      exit 1
    fi

    echo "Looking for the latest successful build with artifacts..."

    for BUILD_ID in $(az pipelines build list \
      --definition-ids $PIPELINE_ID \
      --status completed \
      --result succeeded \
      --top 10 \
      --query '[].id' \
      --output tsv); do

      echo "Checking Build ID: $BUILD_ID"

      ARTIFACT_COUNT=$(az pipelines runs artifact list \
        --run-id $BUILD_ID \
        --query 'length(@)' \
        --output tsv)

      if [ "$ARTIFACT_COUNT" -gt 0 ]; then
        echo "Found build with artifacts: $BUILD_ID"
        SELECTED_BUILD_ID=$BUILD_ID
        break
      fi
    done

    if [ -z "$SELECTED_BUILD_ID" ]; then
      echo "##vso[task.complete result=Failed;]No successful builds with artifacts found in the last 10 builds!"
      exit 1
    fi

    echo "Downloading artifact from Build ID: $SELECTED_BUILD_ID..."
    mkdir -p artifacts
    az pipelines runs artifact download \
      --run-id $SELECTED_BUILD_ID \
      --artifact-name $(artifactName) \
      --path ./artifacts

    echo "Zipping artifact content for deployment..."
    cd artifacts
    zip -r ../deploy.zip .
    cd ..
    ls
  displayName: 'Fetch Last Successful Build That Has Artifacts'
  env:
    MY_DEVOPS_PAT: $(MY_DEVOPS_PAT)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureDevopsConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Applying B1 tier performance & timeout overrides..."
      # 1. WEBSITE_RUN_FROM_PACKAGE=1: Mounts zip instantly (no slow unzip)
      # 2. WEBSITES_CONTAINER_START_TIME_LIMIT=1800: Gives the slow B1 CPU 30 mins to boot before Azure kills it
      az webapp config appsettings set \
        --resource-group $(resourceGroup) \
        --name $(webAppName) \
        --settings WEBSITE_RUN_FROM_PACKAGE=1 \
                 WEBSITES_CONTAINER_START_TIME_LIMIT=1800 \
                 SCM_COMMAND_IDLE_TIMEOUT=600

      echo "Deploying deploy.zip asynchronously..."
      # 3. --async true: Tells the CLI to stop polling and finish the task immediately
      az webapp deploy \
        --resource-group $(resourceGroup) \
        --name $(webAppName) \
        --src-path deploy.zip \
        --type zip \
        --async true
  displayName: 'Deploy Artifact (Async for B1)'
